//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionGoogleDrive.ServiceGoogleDrive {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GoogleDriveFiles", Namespace="http://schemas.datacontract.org/2004/07/ServicioGoogleNube")]
    [System.SerializableAttribute()]
    public partial class GoogleDriveFiles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreatedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> SizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedTime {
            get {
                return this.CreatedTimeField;
            }
            set {
                if ((this.CreatedTimeField.Equals(value) != true)) {
                    this.CreatedTimeField = value;
                    this.RaisePropertyChanged("CreatedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> Size {
            get {
                return this.SizeField;
            }
            set {
                if ((this.SizeField.Equals(value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> Version {
            get {
                return this.VersionField;
            }
            set {
                if ((this.VersionField.Equals(value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceGoogleDrive.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDriveFiles", ReplyAction="http://tempuri.org/IService1/GetDriveFilesResponse")]
        AplicacionGoogleDrive.ServiceGoogleDrive.GoogleDriveFiles[] GetDriveFiles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDriveFiles", ReplyAction="http://tempuri.org/IService1/GetDriveFilesResponse")]
        System.Threading.Tasks.Task<AplicacionGoogleDrive.ServiceGoogleDrive.GoogleDriveFiles[]> GetDriveFilesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FileUpload", ReplyAction="http://tempuri.org/IService1/FileUploadResponse")]
        void FileUpload(System.Web.HttpPostedFileBase file);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FileUpload", ReplyAction="http://tempuri.org/IService1/FileUploadResponse")]
        System.Threading.Tasks.Task FileUploadAsync(System.Web.HttpPostedFileBase file);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DownloadGoogleFile", ReplyAction="http://tempuri.org/IService1/DownloadGoogleFileResponse")]
        string DownloadGoogleFile(string fileId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DownloadGoogleFile", ReplyAction="http://tempuri.org/IService1/DownloadGoogleFileResponse")]
        System.Threading.Tasks.Task<string> DownloadGoogleFileAsync(string fileId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteFile", ReplyAction="http://tempuri.org/IService1/DeleteFileResponse")]
        void DeleteFile(AplicacionGoogleDrive.ServiceGoogleDrive.GoogleDriveFiles files);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteFile", ReplyAction="http://tempuri.org/IService1/DeleteFileResponse")]
        System.Threading.Tasks.Task DeleteFileAsync(AplicacionGoogleDrive.ServiceGoogleDrive.GoogleDriveFiles files);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : AplicacionGoogleDrive.ServiceGoogleDrive.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<AplicacionGoogleDrive.ServiceGoogleDrive.IService1>, AplicacionGoogleDrive.ServiceGoogleDrive.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AplicacionGoogleDrive.ServiceGoogleDrive.GoogleDriveFiles[] GetDriveFiles() {
            return base.Channel.GetDriveFiles();
        }
        
        public System.Threading.Tasks.Task<AplicacionGoogleDrive.ServiceGoogleDrive.GoogleDriveFiles[]> GetDriveFilesAsync() {
            return base.Channel.GetDriveFilesAsync();
        }
        
        public void FileUpload(System.Web.HttpPostedFileBase file) {
            base.Channel.FileUpload(file);
        }
        
        public System.Threading.Tasks.Task FileUploadAsync(System.Web.HttpPostedFileBase file) {
            return base.Channel.FileUploadAsync(file);
        }
        
        public string DownloadGoogleFile(string fileId) {
            return base.Channel.DownloadGoogleFile(fileId);
        }
        
        public System.Threading.Tasks.Task<string> DownloadGoogleFileAsync(string fileId) {
            return base.Channel.DownloadGoogleFileAsync(fileId);
        }
        
        public void DeleteFile(AplicacionGoogleDrive.ServiceGoogleDrive.GoogleDriveFiles files) {
            base.Channel.DeleteFile(files);
        }
        
        public System.Threading.Tasks.Task DeleteFileAsync(AplicacionGoogleDrive.ServiceGoogleDrive.GoogleDriveFiles files) {
            return base.Channel.DeleteFileAsync(files);
        }
    }
}
